### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy_groupies'

### ISSUE THREAD

**Issue by JakaKokosar** [linnarsson-lab/loompy#113]
Hi,

when I upgraded to version 3.* some of the widgets in Orange3-SingleCell add-on stopped working.

```
Name: loompy
Version: 3.0.1
Summary: Work with Loom files for single-cell RNA-seq data
Home-page: https://github.com/linnarsson-lab/loompy
Author: Linnarsson Lab
Author-email: sten.linnarsson@ki.se
License: BSD
Location: /Users/jakakokosar/.pyenv/versions/3.7.4/envs/orange_dev/lib/python3.7/site-packages
Requires: numba, click, scipy, numpy, setuptools, h5py
Required-by: Orange3-SingleCell

```

```
Traceback (most recent call last):
  File "/Users/jakakokosar/Documents/dev/orange-canvas-core/orangecanvas/scheme/widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "/Users/jakakokosar/.pyenv/versions/3.7.4/envs/orange_dev/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "/Users/jakakokosar/.pyenv/versions/3.7.4/envs/orange_dev/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 395, in create_widget_instance
    klass = name_lookup(desc.qualified_name)
  File "/Users/jakakokosar/Documents/dev/orange-canvas-core/orangecanvas/utils/__init__.py", line 71, in name_lookup
    module = __import__(module_name, fromlist=[class_name])
  File "/Users/jakakokosar/Documents/dev/orange3-single-cell/orangecontrib/single_cell/widgets/owmultisample.py", line 21, in <module>
    from orangecontrib.single_cell.widgets.load_data import Concatenate, Loader
  File "/Users/jakakokosar/Documents/dev/orange3-single-cell/orangecontrib/single_cell/widgets/load_data.py", line 10, in <module>
    import loompy as lp
  File "/Users/jakakokosar/.pyenv/versions/3.7.4/envs/orange_dev/lib/python3.7/site-packages/loompy/__init__.py", line 11, in <module>
    from .loompy import connect, create, create_append, combine, create_from_cellranger, LoomConnection, new, combine_faster, create_from_matrix_market
  File "/Users/jakakokosar/.pyenv/versions/3.7.4/envs/orange_dev/lib/python3.7/site-packages/loompy/loompy.py", line 33, in <module>
    import numpy_groupies.aggregate_numpy as npg
ModuleNotFoundError: No module named 'numpy_groupies'
------------------------ ModuleNotFoundError Exception ------------------------

```

However, this does not happen on version 2.*
I think numpy_groupies should be listed as a requirement or am I missing something here?

**Comment by slinnarsson** [comment]
Hi

Yes I missed that dependency, but it was already fixed in 3.0.2. I will push to pypi shortly. For now, you can get around it by installing numpy-groupies first (`pip install numpy-groupies`).

**Comment by ivirshup** [comment]
@slinnarsson would you mind pinging here when you've pushed to pypi?

**Comment by slinnarsson** [comment]
loompy 3.0.3 should be on PyPi now!

**Comment by ivirshup** [comment]
Thanks!
