### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by dnehar** [linnarsson-lab/loompy#114]
Hi, 
I was trying to generate a loom file from fastq files following this (https://linnarssonlab.org/loompy/kallisto/index.html). I am facing the following issue . 
Traceback (most recent call last):
  File "/home/nehard/anaconda3/envs/velo/bin/loompy", line 10, in <module>
    sys.exit(cli())
  File "/home/nehard/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/nehard/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/nehard/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nehard/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nehard/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/nehard/anaconda3/envs/velo/lib/python3.6/site-packages/loompy/commands.py", line 34, in fromfq
    create_from_fastq(loomfile, sampleid, list(fastqs), indexdir, metadatafile, threads)
  File "/home/nehard/anaconda3/envs/velo/lib/python3.6/site-packages/loompy/bus_file.py", line 416, in create_from_fastq
    for line in execute(cmd, synchronous):
  File "/home/nehard/anaconda3/envs/velo/lib/python3.6/site-packages/loompy/bus_file.py", line 357, in execute
    popen = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'text'

Any suggestions ? 
Thanks for the help !

**Comment by slinnarsson** [comment]
Seems that the `text` parameter is Python 3.7-only. I replaced it with the previous parameter name, which should work in older Python distros. I will push it together with other bugfixes today.

**Comment by dnehar** [comment]
Thank you !
Now I am facing the following issue: 
    return self.__setattr__(name, val)
  File "/home/nehard/anaconda3/envs/velo/lib/python3.6/site-packages/loompy-3.0.3-py3.6.egg/loompy/attribute_manager.py", line 157, in __setattr__
    self.ds._file.create_dataset(a + name, data=values, dtype=h5py.string_dtype(encoding="utf-8"))
AttributeError: module 'h5py' has no attribute 'string_dtype'

and I had to run  to get it start:
export LANG=en_US.UTF-8 LANGUAGE=en_US.en LC_ALL=en_US.UTF-8

The  fromfq is generating a .loom file (as expected), which can't be read. 

Hope you can help !
Thank you,

**Comment by slinnarsson** [comment]
I think you need to update h5py. Loompy requires h5py 2.10.0 or higher. Let me know if that helps!

**Comment by dnehar** [comment]
Thank you very much. In fact, updating h5py resolved the problem. 
I did the following: 
1- updating h5py to 2.10.0 (pip install --upgrade --no-binary=h5py h5py), threw the following error (due to dvpt version of scanpy): " scanpy 1.4.5.dev134+gd9c6f0a has requirement h5py!=2.10.0, but you'll have h5py 2.10.0 which is incompatible."
2- I've created a new py env:
installed loompy, loaded kallisto and bustools
The running time time was ~ 1h:30, when cellranger + Velocyto pipeline ~10h (using the same fastq file) ! 
Thanks

**Comment by slinnarsson** [comment]
It's unfortunate that scanpy depends on h5py!=2.10.0 and loompy requires 2.10.0. I fixed this and made a new release (3.0.6) that no longer requires h5py 2.10.0.
