### ISSUE TITLE
h5py error: "OSError: Unable to create file ..."

### ISSUE THREAD

**Issue by pburnham50** [linnarsson-lab/loompy#115]
Hi, just tried running the loompy from fastq using the tutorial files. Everything ran fine up to the last step. I tried uninstalling and reinstalling h5py per suggestions from similar errors on stack exchange - that did not work though. Was wondering if you had any suggestions.

Loompy v3.0.2 by Linnarsson Lab 🌸 (http://linnarssonlab.org & http://loompy.org)

2019-10-01 14:38:26,320 - INFO - Using 6 threads.
2019-10-01 14:38:26,322 - INFO - kallisto bus -i human_GRCh38_gencode.v31/gencode.v31.fragments.idx -o /var/folders/f6/kq8244v13cq8wqgw0l422xsw0000gn/T/tmpaasqn0n9 -x 10xv3 -t 6 pbmc_1k_v3_S1_L001_R1_001.fastq.gz pbmc_1k_v3_S1_L001_R2_001.fastq.gz pbmc_1k_v3_S1_L002_R1_001.fastq.gz pbmc_1k_v3_S1_L002_R2_001.fastq.gz
2019-10-01 14:38:26,391 - INFO - [index] k-mer length: 31
2019-10-01 14:38:26,392 - INFO - [index] number of targets: 845,338
2019-10-01 14:38:26,392 - INFO - [index] number of k-mers: 271,648,279
2019-10-01 14:39:15,947 - INFO - [index] number of equivalence classes: 4,776,424
2019-10-01 14:39:33,798 - INFO - [quant] will process sample 1: pbmc_1k_v3_S1_L001_R1_001.fastq.gz
2019-10-01 14:39:33,798 - INFO -                                pbmc_1k_v3_S1_L001_R2_001.fastq.gz
2019-10-01 14:39:33,798 - INFO - [quant] will process sample 2: pbmc_1k_v3_S1_L002_R1_001.fastq.gz
2019-10-01 14:39:33,798 - INFO -                                pbmc_1k_v3_S1_L002_R2_001.fastq.gz
2019-10-01 14:42:29,568 - INFO - [quant] finding pseudoalignments for the reads ... done
2019-10-01 14:42:29,572 - INFO - [quant] processed 66,601,887 reads, 47,826,751 reads pseudoaligned
2019-10-01 14:42:49,160 - INFO - Loading gene metadata
2019-10-01 14:42:49,589 - INFO - Loading fragments-to-gene mappings
2019-10-01 14:42:50,125 - INFO - Indexing genes
2019-10-01 14:42:50,488 - INFO - Loading equivalence classes
2019-10-01 14:43:20,647 - INFO - Mapping equivalence classes to genes
2019-10-01 14:43:31,258 - INFO - Loading fragment IDs
2019-10-01 14:43:31,614 - INFO - Loading BUS records
2019-10-01 14:44:46,333 - INFO - Sorting cell IDs
2019-10-01 14:44:48,587 - INFO - Found 47,826,751 records for 60,662 genes and 572,948 uncorrected cell barcodes.
2019-10-01 14:44:48,588 - INFO - Correcting cell barcodes
2019-10-01 14:46:54,156 - INFO - Found 312,447 corrected cell barcodes.
2019-10-01 14:46:54,157 - INFO - Removing redundant reads using UMIs
2019-10-01 14:47:33,616 - INFO - 71% sequencing saturation.
2019-10-01 14:47:33,616 - INFO - Counting pseudoalignments for main matrix
2019-10-01 14:47:39,444 - INFO - Found 5,105,024 UMIs.
2019-10-01 14:47:40,069 - INFO - Counting pseudoalignments for layer 'unspliced'
2019-10-01 14:48:48,582 - INFO - Found 2,503,880 UMIs.
2019-10-01 14:48:49,050 - INFO - Counting pseudoalignments for layer 'spliced'
2019-10-01 14:49:56,069 - INFO - Found 3,278,570 UMIs.
2019-10-01 14:49:56,069 - INFO - Calling cells
2019-10-01 14:52:58,767 - INFO - Found 1189 valid cells and ~79 ambient UMIs.
2019-10-01 14:52:58,767 - INFO - Creating loom file '1kPBMC.loom'
2019-10-01 14:52:58,767 - INFO - Saving
Traceback (most recent call last):
  File "/Users/pburnham/miniconda3/bin/loompy", line 11, in <module>
    load_entry_point('loompy==3.0.2', 'console_scripts', 'loompy')()
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/loompy-3.0.2-py3.7.egg/loompy/commands.py", line 34, in fromfq
    create_from_fastq(loomfile, sampleid, list(fastqs), indexdir, metadatafile, threads)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/loompy-3.0.2-py3.7.egg/loompy/bus_file.py", line 455, in create_from_fastq
    bus.save(out_file, sample_id, samples_metadata_file)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/loompy-3.0.2-py3.7.egg/loompy/bus_file.py", line 350, in save
    create(out_file, layers, row_attrs, col_attrs, file_attrs=global_attrs)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/loompy-3.0.2-py3.7.egg/loompy/loompy.py", line 1057, in create
    with new(filename, file_attrs=file_attrs) as ds:
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/loompy-3.0.2-py3.7.egg/loompy/loompy.py", line 983, in new
    f = h5py.File(name=filename, mode='w')
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/Users/pburnham/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')

**Comment by slinnarsson** [comment]
Hm. Not sure what's going on there. That error usually happens when you try to open a file (for writing) that was already open in another process. Did the output loom file already exist? If so, can you retry after first deleting the file? In principle I think the `f = h5py.File(name=filename, mode='w')` call should overwrite an existing file, but maybe not if it was also open in another process.

**Comment by pburnham50** [comment]
Hi Sten, thanks for replying so promptly. I think that was the issue. The first time I ran there was an error which I was able to fix, but the erroneous loom file was still created and I didn't delete before re-running. Thanks for your help and the great software.

**Comment by slinnarsson** [comment]
👍
