### ISSUE TITLE
Loom file not generated

### ISSUE THREAD

**Issue by whelena** [linnarsson-lab/loompy#129]
I ran loompy from fq using this command:
`loompy fromfq --threads 4 loom/R282_run1_Negative.loom R282_run1_Negative human_GRCh38_gencode.v31.600 datasheet.tsv R282_run1_Negative_L001_R1_001.fastq.gz 
R282_run1_Negative_L001_R2_001.fastq.gz 
R282_run1_Negative_L002_R1_001.fastq.gz R282_run1_Negative_L002_R2_001.fastq.gz R282_run1_Negative_L003_R1_001.fastq.gz R282_run1_Negative_L003_R2_001.fastq.gz R282_run1_Negative_L004_R1_001.fastq.gz R282_run1_Negative_L004_R2_001.fastq.gz &> logs/R282_run1_Negative_fromfq.log`

The fastq files are Cellranger 3.0 output and I'm using Python 3.8.2 and loompy 3.0.2
I got no loomfiles in my output directory and the output messages I got is:

`
Loompy v3.0.6 by Linnarsson Lab 🌸 (http://linnarssonlab.org & http://loompy.org)

2020-05-14 21:54:54,648 - INFO - Using 4 threads.
2020-05-14 21:54:54,653 - INFO - kallisto bus -i data/human_GRCh38_gencode.v31.600/gencode.v31.fragments.idx -o /tmp/tmpjm44abme -x 10xv2 -t 4 data/CR_output/R282_run1/R282_run1_Negative_L001_R1_001.fastq.gz data/CR_output/R282_run1/R28
2_run1_Negative_L001_R2_001.fastq.gz data/CR_output/R282_run1/R282_run1_Negative_L002_R1_001.fastq.gz data/CR_output/R282_run1/R282_run1_Negative_L002_R2_001.fastq.gz data/CR_output/R282_run1/R282_run1_Negative_L003_R1_001.fastq.gz data
/CR_output/R282_run1/R282_run1_Negative_L003_R2_001.fastq.gz data/CR_output/R282_run1/R282_run1_Negative_L004_R1_001.fastq.gz data/CR_output/R282_run1/R282_run1_Negative_L004_R2_001.fastq.gz
2020-05-14 21:54:54,700 - INFO - [index] k-mer length: 31
2020-05-14 21:54:54,700 - INFO - [index] number of targets: 845,338
2020-05-14 21:54:54,700 - INFO - [index] number of k-mers: 271,648,279
2020-05-14 21:55:28,039 - INFO - [index] number of equivalence classes: 4,776,424
2020-05-14 21:55:43,497 - INFO - [quant] will process sample 1: data/CR_output/R282_run1/R282_run1_Negative_L001_R1_001.fastq.gz
2020-05-14 21:55:43,497 - INFO -                                data/CR_output/R282_run1/R282_run1_Negative_L001_R2_001.fastq.gz
2020-05-14 21:55:43,498 - INFO - [quant] will process sample 2: data/CR_output/R282_run1/R282_run1_Negative_L002_R1_001.fastq.gz
2020-05-14 21:55:43,498 - INFO -                                data/CR_output/R282_run1/R282_run1_Negative_L002_R2_001.fastq.gz
2020-05-14 21:55:43,498 - INFO - [quant] will process sample 3: data/CR_output/R282_run1/R282_run1_Negative_L003_R1_001.fastq.gz
2020-05-14 21:55:43,498 - INFO -                                data/CR_output/R282_run1/R282_run1_Negative_L003_R2_001.fastq.gz
2020-05-14 21:55:43,498 - INFO - [quant] will process sample 4: data/CR_output/R282_run1/R282_run1_Negative_L004_R1_001.fastq.gz
2020-05-14 21:55:43,498 - INFO -                                data/CR_output/R282_run1/R282_run1_Negative_L004_R2_001.fastq.gz
2020-05-14 22:04:37,860 - INFO - [quant] finding pseudoalignments for the reads ... done
2020-05-14 22:04:37,861 - INFO - [quant] processed 135,471,737 reads, 89,058,785 reads pseudoaligned
2020-05-14 22:04:49,702 - INFO - Loading gene metadata
2020-05-14 22:04:50,022 - INFO - Loading fragments-to-gene mappings
2020-05-14 22:04:50,594 - INFO - Indexing genes
2020-05-14 22:04:51,022 - INFO - Loading equivalence classes
2020-05-14 22:05:26,323 - INFO - Mapping equivalence classes to genes
2020-05-14 22:05:41,852 - INFO - Loading fragment IDs
2020-05-14 22:05:42,291 - INFO - Loading BUS records
Traceback (most recent call last):
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/bin/loompy", line 8, in <module>
    sys.exit(cli())
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/loompy/commands.py", line 34, in fromfq
    create_from_fastq(loomfile, sampleid, list(fastqs), indexdir, metadatafile, threads)
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/loompy/bus_file.py", line 429, in create_from_fastq
    bus = BusFile(
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/loompy/bus_file.py", line 239, in __init__
    self.bus_gene = np.array([self.gene_for_ec[x] for x in self.bus["equivalence_class"]], dtype=np.int32)
  File "/home/BCRICWH.LAN/helena.winata/.conda/envs/scvelo/lib/python3.8/site-packages/loompy/bus_file.py", line 239, in <listcomp>
    self.bus_gene = np.array([self.gene_for_ec[x] for x in self.bus["equivalence_class"]], dtype=np.int32)
KeyError: 9588922
`

**Comment by ElinorWing** [comment]
Hello, 
I know it has been a couple of years since you posted but did you manage to solve this? I am currently having the same issue.
Thanks,
Elnior

**Comment by whelena** [comment]
I ended up going a different way entirely and not use loom at all
