### ISSUE TITLE
Cannot import loom file from Seurat (UnicodeDecodeError)

### ISSUE THREAD

**Issue by abeaude** [linnarsson-lab/loompy#132]
Hi, 
I used to export my seurat object to loom file with the `as.loom` function and the loomR package. 
But now I cannot anymore import them in scanpy I get the following error : 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda3/envs/scanpy/lib/python3.8/site-packages/scanpy/readwrite.py", line 112, in read
    return _read(
  File "~/anaconda3/envs/scanpy/lib/python3.8/site-packages/scanpy/readwrite.py", line 717, in _read
    adata = read_loom(filename=filename, **kwargs)
  File "~/anaconda3/envs/scanpy/lib/python3.8/site-packages/anndata/_io/read.py", line 209, in read_loom
    obs = dict(lc.col_attrs)
  File "~anaconda3/envs/scanpy/lib/python3.8/site-packages/loompy/attribute_manager.py", line 102, in __getitem__
    return self.__getattr__(thing)
  File "~/anaconda3/envs/scanpy/lib/python3.8/site-packages/loompy/attribute_manager.py", line 119, in __getattr__
    vals = loompy.materialize_attr_values(self.ds._file[a][name][:])
  File "~/anaconda3/envs/scanpy/lib/python3.8/site-packages/loompy/normalize.py", line 98, in materialize_attr_values
    result = np.array([html.unescape(x) for x in temp.astype(str)], dtype=object)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10: ordinal not in range(128)
```
I tried with different dataset, different versions but always getting this error. 

Do you have any idea how to solve this ? 

Installed versions : 
scanpy==1.5.1 anndata==0.7.3 umap==0.4.4 numpy==1.17.5 scipy==1.4.1 pandas==1.0.4 scikit-learn==0.23.1 statsmodels==0.11.1 python-igraph==0.8.2 leidenalg==0.8.0
loompy==3.0.6

**Comment by abeaude** [comment]
I finnaly found what was causing the issue. 
I read the loom file manually to find the part causing the problem. Actually one entry in my metadata was not correctly encoded. 
It's working now for me. 
But I was surprised, loompy is stricter than loomR. I had no trouble importing my loom file with loomR.
