### ISSUE TITLE
"AttributeError: 'list' object has no attribute 'shape'" in saving loom file using loompy fromfq

### ISSUE THREAD

**Issue by Malindrie** [linnarsson-lab/loompy#137]
Hello,

I used the loompy command line tool to create a loom file from fastqs. Everything runs well until the save loom file step. I get the error "AttributeError: 'list' object has no attribute 'shape'". Any help with this is much appreciated. Below I have copied the output I get. 

2020-10-07 07:24:44,050 - INFO - [index] k-mer length: 31
2020-10-07 07:24:44,050 - INFO - [index] number of targets: 845,338
2020-10-07 07:24:44,051 - INFO - [index] number of k-mers: 271,648,279
2020-10-07 07:25:18,395 - INFO - [index] number of equivalence classes: 4,776,424
2020-10-07 07:25:37,539 - INFO - [quant] will process sample 1: /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L001_R1_001.fastq.gz
2020-10-07 07:25:37,539 - INFO -                                /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L001_R2_001.fastq.gz
2020-10-07 07:25:37,539 - INFO - [quant] will process sample 2: /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L002_R1_001.fastq.gz
2020-10-07 07:25:37,539 - INFO -                                /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L002_R2_001.fastq.gz
2020-10-07 07:25:37,539 - INFO - [quant] will process sample 3: /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L003_R1_001.fastq.gz
2020-10-07 07:25:37,539 - INFO -                                /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L003_R2_001.fastq.gz
2020-10-07 07:25:37,540 - INFO - [quant] will process sample 4: /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L004_R1_001.fastq.gz
2020-10-07 07:25:37,540 - INFO -                                /QRISdata/Q3112/seq_data/WOLV-0001/cellranger/fastq/combined/A3_d40/A3_d40_S2_L004_R2_001.fastq.gz
2020-10-07 07:32:44,594 - INFO - [quant] finding pseudoalignments for the reads ... done
2020-10-07 07:32:44,595 - INFO - [quant] processed 188,630,497 reads, 134,736,788 reads pseudoaligned
2020-10-07 07:33:00,865 - INFO - Loading gene metadata
2020-10-07 07:33:01,452 - INFO - Loading fragments-to-gene mappings
2020-10-07 07:33:02,204 - INFO - Indexing genes
2020-10-07 07:33:02,689 - INFO - Loading equivalence classes
2020-10-07 07:33:39,213 - INFO - Mapping equivalence classes to genes
2020-10-07 07:33:54,288 - INFO - Loading fragment IDs
2020-10-07 07:33:54,609 - INFO - Loading BUS records
2020-10-07 07:38:05,403 - INFO - Sorting cell IDs
2020-10-07 07:38:13,811 - INFO - Found 134,736,788 records for 60,662 genes and 1,831,180 uncorrected cell barcodes.
2020-10-07 07:38:13,812 - INFO - Correcting cell barcodes
2020-10-07 07:43:14,571 - INFO - Found 488,409 corrected cell barcodes.
2020-10-07 07:43:14,572 - INFO - Removing redundant reads using UMIs
2020-10-07 07:45:35,084 - INFO - 51% sequencing saturation.
2020-10-07 07:45:35,085 - INFO - Counting pseudoalignments for main matrix
2020-10-07 07:46:13,002 - INFO - Found 33,990,938 UMIs.
2020-10-07 07:46:13,964 - INFO - Counting pseudoalignments for layer 'unspliced'
2020-10-07 07:50:35,962 - INFO - Found 15,647,623 UMIs.
2020-10-07 07:50:36,665 - INFO - Counting pseudoalignments for layer 'spliced'
2020-10-07 07:55:53,793 - INFO - Found 21,902,684 UMIs.
2020-10-07 07:55:53,793 - INFO - Calling cells
2020-10-07 07:59:21,991 - INFO - Found 12782 valid cells and ~6281 ambient UMIs.
2020-10-07 07:59:21,991 - INFO - Creating loom file 'DWSY.loom'
2020-10-07 07:59:21,991 - INFO - Saving
Traceback (most recent call last):
  File "/home/s4566105/miniconda3/envs/r_newenv/bin/loompy", line 8, in <module>
    sys.exit(cli())
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/loompy/commands.py", line 34, in fromfq
    create_from_fastq(loomfile, sampleid, list(fastqs), indexdir, metadatafile, threads)
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/loompy/bus_file.py", line 455, in create_from_fastq
    bus.save(out_file, sample_id, samples_metadata_file)
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/loompy/bus_file.py", line 350, in save
    create(out_file, layers, row_attrs, col_attrs, file_attrs=global_attrs)
  File "/home/s4566105/miniconda3/envs/r_newenv/lib/python3.7/site-packages/loompy/loompy.py", line 985, in create
    if ra.shape[0] != shape[0]:
AttributeError: 'list' object has no attribute 'shape'

**Comment by slinnarsson** [comment]
I think I've fixed the bug now. Pull the latest version and see if it works.
