### ISSUE TITLE
Error decoding run_info.json

### ISSUE THREAD

**Issue by MagpiePKU** [linnarsson-lab/loompy#140]
Hi,

Thanks for creating this very useful tool. We ran loompy without error previously but recently (after a few other package installations) we got a problem in generating new loom files using loompy fromfq: 

##
 Log: 
Loompy v3.0.6 by Linnarsson Lab 🌸 (http://linnarssonlab.org & http://loompy.org)

2020-11-13 16:09:33,094 - INFO - Using 24 threads.
2020-11-13 16:09:33,117 - INFO - kallisto bus -i /gpfs/genomedb/kallisto/loompy/human_GRCh38_gencode.v31.600/gencode.v31.fragments.idx -o /tmp/tmp5iro5obk -x 10xv3 -t 24 /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S5_L003_R1_001.fastq.gz /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S5_L003_R2_001.fastq.gz /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S6_L003_R1_001.fastq.gz /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S6_L003_R2_001.fastq.gz /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S7_L003_R1_001.fastq.gz /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S7_L003_R2_001.fastq.gz
2020-11-13 16:09:33,328 - INFO - [index] k-mer length: 31
2020-11-13 16:09:33,328 - INFO - [index] number of targets: 845,338
2020-11-13 16:09:33,328 - INFO - [index] number of k-mers: 271,648,279
2020-11-13 16:10:03,506 - INFO - [index] number of equivalence classes: 4,776,424
2020-11-13 16:10:18,297 - INFO - [quant] will process sample 1: /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S5_L003_R1_001.fastq.gz
2020-11-13 16:10:18,299 - INFO -                                /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S5_L003_R2_001.fastq.gz
2020-11-13 16:10:18,299 - INFO - [quant] will process sample 2: /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S6_L003_R1_001.fastq.gz
2020-11-13 16:10:18,300 - INFO -                                /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S6_L003_R2_001.fastq.gz
2020-11-13 16:10:18,300 - INFO - [quant] will process sample 3: /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S7_L003_R1_001.fastq.gz
2020-11-13 16:10:18,300 - INFO -                                /gpfs/datatransfer/c03b01n04/sdb1-20201110_17/LBFC20201489/201107_A00682_0472_BHKY5KDSXY/20044378S4-10XSC3_S7_L003_R2_001.fastq.gz
2020-11-13 17:09:53,297 - INFO - [quant] finding pseudoalignments for the reads ... done
2020-11-13 17:09:53,300 - INFO - [quant] processed 946,138,749 reads, 683,048,253 reads pseudoaligned
2020-11-13 17:09:58,179 - ERROR - Error decoding run_info.json: Expecting value: line 1 column 1 (char 0)
2020-11-13 17:09:58,180 - INFO - Loading gene metadata
2020-11-13 17:09:58,592 - INFO - Loading fragments-to-gene mappings
2020-11-13 17:09:59,165 - INFO - Indexing genes
2020-11-13 17:09:59,668 - INFO - Loading equivalence classes
2020-11-13 17:09:59,668 - INFO - Mapping equivalence classes to genes
2020-11-13 17:09:59,668 - INFO - Loading fragment IDs
2020-11-13 17:09:59,669 - INFO - Loading BUS records
##
Err:
Traceback (most recent call last):
  File "/gpfs/bin/anaconda3-gpu/bin/loompy", line 8, in <module>
    sys.exit(cli())
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/loompy/commands.py", line 34, in fromfq
    create_from_fastq(loomfile, sampleid, list(fastqs), indexdir, metadatafile, threads)
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/loompy/bus_file.py", line 429, in create_from_fastq
    bus = BusFile(
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/loompy/bus_file.py", line 239, in __init__
    self.bus_gene = np.array([self.gene_for_ec[x] for x in self.bus["equivalence_class"]], dtype=np.int32)
  File "/gpfs/bin/anaconda3-gpu/lib/python3.8/site-packages/loompy/bus_file.py", line 239, in <listcomp>
    self.bus_gene = np.array([self.gene_for_ec[x] for x in self.bus["equivalence_class"]], dtype=np.int32)
KeyError: 658005
## 

We wonder how could we fix it. 

Thanks a lot ,
Yi

**Comment by slinnarsson** [comment]
Hi! I've seen this occasionally and it might be related to kallisto. Could you try updating kallisto? Alternatively, there's a new tool called "kb" from Pachter lab which is essentially equivalent to loompy fromfq (but faster, since it's C++) and generates loom files.

**Comment by josinejansen** [comment]
Hi, I an trying to create loom file for the first time, but right now I am stumbling upon this error: 

"Manifest file 'manifest.json' was missing from index"

This is my code:
`loompy.create_from_fastq('myloombasedon_fq', 'human_GRCh38_gencode.v31', adata.var, 'GBM-TIL_HHT_S6_L002_R2_001.fastq.gz', 'GBM-TIL_HHT_S6_L002_R1_001.fastq.gz')`

What am I doing wrong?
Your help is greatly appreciated!

Josine
