### ISSUE TITLE
LoomR and ScopeLoomR can read these two files, but Loompy reports that it cannot read them.

### ISSUE THREAD

**Issue by sunjiahe-hub** [linnarsson-lab/loompy#171]
Hi, in the process of my analysis. I found that these two files cannot be read by Loompy, and the following error will be reported. I tried to use LoomR and ScopeLoomR to read the files, and found that they can be read. I hope to get your help, thank you.
I am sending you the question file by email, hoping to get your attention.

`E:\anaconda3\python.exe D:/sgs-project/LoomParser/LoomParser.py
Traceback (most recent call last):
  File "D:/sgs-project/LoomParser/LoomParser.py", line 58, in <module>
    LoomParser(in_file_path, out_file_path)
  File "D:/sgs-project/LoomParser/LoomParser.py", line 24, in LoomParser
    ds = loompy.connect(in_file_path)
  File "E:\anaconda3\lib\site-packages\loompy\loompy.py", line 1515, in connect
    return LoomConnection(filename, mode, validate=validate)
  File "E:\anaconda3\lib\site-packages\loompy\loompy.py", line 86, in __init__
    raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appear to be a valid Loom file according to Loom spec version '{lv.version}'")
ValueError: Row attribute 'Gene' dtype object is not allowed
Column attribute 'CellID' dtype object is not allowed
Column attribute 'Embedding' dtype [('_X', '<f8'), ('_Y', '<f8')] is not allowed
Column attribute 'Embeddings_X' dtype [('-1', '<f8')] is not allowed
Column attribute 'Embeddings_Y' dtype [('-1', '<f8')] is not allowed
Column attribute 'annotation' dtype object is not allowed
Column attribute 'cluster' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
./data/5_GSE176173_Talon_Naive_TSC_PRC2_loom.loom does not appear to be a valid Loom file according to Loom spec version '0.0.0'

Process finished with exit code 1`

**Comment by sunjiahe-hub** [comment]
出现问题无法被Loompy解析的两个文件的下载地址：

https://ftp.ncbi.nlm.nih.gov/geo/series/GSE176nnn/GSE176173/suppl/GSE176173_Talon_Naive_TSC_PRC2_loom.loom.gz
https://ftp.ncbi.nlm.nih.gov/geo/series/GSE176nnn/GSE176173/suppl/GSE176173_Talon_Naive_TSC_PRC2_loom.loom.gz

**Comment by pl-ki** [comment]
Add 'validate=False' to loompy.connect().
