### ISSUE TITLE
loompy.combine 

### ISSUE THREAD

**Issue by anafilia** [linnarsson-lab/loompy#178]
Hello,
I am merging multiple loom files using:

loompy.combine(file_names, output_file=out, key="Accession")

and I get multiple warning messages every time  it merges a file (which I suppose I ignore) but after a while merging stops and I get the following error. Any help would be appreciated. Thank you!

WARNING:root:╭── 'batch_scan_layers' is deprecated. Use 'scan' instead
WARNING:root:╰──> at /opt/anaconda3/lib/python3.9/site-packages/loompy/loompy.py, line 465
Traceback (most recent call last):

  File "/var/folders/gf/b1kqttd500zd2d5pcj1lkb7c0000gn/T/ipykernel_3219/1663153508.py", line 1, in <module>
    loompy.combine(file_names, output_file=out, key="Accession")

  File "/opt/anaconda3/lib/python3.9/site-packages/loompy/loompy.py", line 1264, in combine
    ds.add_loom(f, key, batch_size=batch_size, convert_attrs=convert_attrs)

  File "/opt/anaconda3/lib/python3.9/site-packages/loompy/loompy.py", line 426, in add_loom
    with loompy.connect(other_file) as other:

  File "/opt/anaconda3/lib/python3.9/site-packages/loompy/loompy.py", line 1389, in connect
    return LoomConnection(filename, mode, validate=validate)

  File "/opt/anaconda3/lib/python3.9/site-packages/loompy/loompy.py", line 81, in __init__
    if not lv.validate(filename):

  File "/opt/anaconda3/lib/python3.9/site-packages/loompy/loom_validator.py", line 48, in validate
    with h5py.File(path, mode="r") as f:

  File "/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)

  File "/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5f.pyx", line 106, in h5py.h5f.open

OSError: Unable to open file (file signature not found)

**Comment by pl-ki** [comment]
Seems that the loom/hdf5 file is corrupted, since the message comes from h5py, not loompy.
Try opening each input file with h5py.File() and see which fails.
