### ISSUE TITLE
Tests fail with "to_html"

### ISSUE THREAD

**Issue by rekado** [linnarsson-lab/loompy#37]
I have packaged loompy for Guix and it seems to build fine.  However, running the tests with "python setup.py test" (before installing the package) results in an error:

```
running "python setup.py" with command "test" and parameters ()
running test
running egg_info
writing loompy.egg-info/PKG-INFO
writing dependency_links to loompy.egg-info/dependency_links.txt
writing requirements to loompy.egg-info/requires.txt
writing top-level names to loompy.egg-info/top_level.txt
warning: manifest_maker: standard file '-c' not found

reading manifest file 'loompy.egg-info/SOURCES.txt'
writing manifest file 'loompy.egg-info/SOURCES.txt'
running build_ext
/gnu/store/svmbly6mlrmasgh4nda1wclnvdkadyx6-python-h5py-2.7.0/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 18, in <module>
    url="https://github.com/linnarsson-lab/loompy"
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/site-packages/setuptools/command/test.py", line 210, in run
    self.run_tests()
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/site-packages/setuptools/command/test.py", line 231, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/unittest/main.py", line 124, in parseArgs
    self._do_discovery([])
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/gnu/store/3lkypf5wnsnvkaidhw0pv7k3yjfh1r9g-python-3.6.3/lib/python3.6/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
TypeError: to_html() missing 1 required positional argument: 'ds'

```

I wonder if this indicates some confusion over `to_html` (which is provided by loompy) and some other implementation of `to_html` which is expected here.  Is there another way I should run the tests?

**Comment by slinnarsson** [comment]
We don't yet have unit tests for loompy (see #36), so I don't think `python setup.py test` is even expected to work. It seems to try to call `to_html()` without an argument, which will not work. Probably the auto-discovery of unit tests has failed and somehow thinks `to_html()` is a test function.

I suggest ignoring this, until the day we have a proper test suite.
