### ISSUE TITLE
Loom objects completely broken?

### ISSUE THREAD

**Issue by lamdan2** [linnarsson-lab/loompy#65]
I am getting this type of effect below. This applies for different loom files, and different versions of hdf5. Any ideas? Am I missing something stupid? Please help!

>>> import loompy
>>> ds = loompy.connect("L6_Hindbrain_neurons.loom")
>>> ds
<loompy.loompy.LoomConnection object at 0x7efb360304a8>
>>> ds[ds.ca.Gene == "Actb", :]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'LoomConnection' object has no attribute 'ca'
>>> ds.shape()
(27998, 1144)
>>> ds[0:10, 0:10]
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 4.,  2.,  3.,  3.,  2.,  6.,  1.,  5.,  6.,  4.],
       [ 0.,  0.,  0.,  0.,  8.,  3.,  3.,  5.,  7., 16.],
       [ 2.,  0.,  1.,  0.,  4.,  4.,  6.,  3.,  3.,  8.],
       [ 7.,  0.,  2.,  0.,  0.,  5.,  4.,  0.,  1.,  4.],
       [ 0.,  0.,  3.,  0.,  3.,  6.,  5.,  4.,  4., 10.],
       [ 1.,  0.,  4.,  4.,  5., 11.,  4., 11.,  2., 10.],
       [ 2.,  0.,  4.,  0., 11.,  7.,  5.,  5.,  2., 10.],
       [ 7.,  9.,  8.,  6.,  6., 12.,  6.,  6., 10., 11.]], dtype=float32)
>>> ds.attrs.title
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'LoomAttributeManager' object has no attribute 'title'
>>> ds.attrs
<loompy.loompy.LoomAttributeManager object at 0x7efb3d5e4eb8>

**Comment by lamdan2** [comment]
OK think I have solved this with correct indexing. Apologies!
