### ISSUE TITLE
Fails with python-2.7

### ISSUE THREAD

**Issue by yurivict** [linnarsson-lab/loompy#75]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 26
    download_url=f"https://github.com/linnarsson-lab/loompy/archive/{__version__}.tar.gz",
                                                                                        ^
SyntaxError: invalid syntax
*** Error code 1
```

OS: FreeBSD 11.2

**Comment by slinnarsson** [comment]
Loompy requires Python 3.6. This is now better explained in the installation docs, and I added an explicit check in setup.py.
