### ISSUE TITLE
SyntaxError: invalid syntax installing loompy

### ISSUE THREAD

**Issue by kgerman73** [linnarsson-lab/loompy#81]
I have python 3.6.5 installed but still get an error installing loompy:

# pip install loompy
Collecting loompy
  Using cached https://files.pythonhosted.org/packages/18/38/6231e36536a3741e2cc10fada493b8f1d900a57f13f6b416528a195fc601/loompy-2.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-T2hzZu/loompy/setup.py", line 26
        download_url=f"https://github.com/linnarsson-lab/loompy/archive/{__version__}.tar.gz",
                                                                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-T2hzZu/loompy/

# python3 --version
Python 3.6.5

**Comment by kgerman73** [comment]
DOH!  I was using pip and not pip3.  NVM!
