### ISSUE TITLE
Performance of loompy.combine()

### ISSUE THREAD

**Issue by slinnarsson** [linnarsson-lab/loompy#97]
It's very slow. Try to make it faster by preallocating all the necessary space.

**Comment by simone-codeluppi** [comment]
I run a test on some loompy files created from smFISH counting location:

`/fish/simone_processing/simone_data/test_new_cfg_name/EXP-19-CX9100_Excitatory_Hybridization01_TxRed/EXP-19-CX9100_Excitatory_Hybridization01_TxRed_single_fov_counting_tmp`

The `loompy.combine` works without issues while I get the following error from the `loompy.combine_faster` (the code is the same, changes only the function call):

```python
Traceback (most recent call last):
 File "/fish/simone_processing/anaconda3/envs/htc_env/lib/python3.7/site-packages/h5py/_hl/selections.py", line 85, in select
 int(a)
TypeError: only size-1 arrays can be converted to Python scalars

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "pysmFISH_v2/combine_counting_fov.py", line 73, in <module>
 main()
 File "pysmFISH_v2/combine_counting_fov.py", line 69, in main
 merging = merge_fov_counting(pipeline_config_fpath,tmp_counting_dir_path)
 File "pysmFISH_v2/combine_counting_fov.py", line 28, in __init__
 self.merge_loom()
 File "pysmFISH_v2/combine_counting_fov.py", line 41, in merge_loom
 loompy.combine_faster(self.merge_loom_fpaths, merged_countings_fpath, key="coords")
 File "/fish/simone_processing/Code/loompy/loompy/loompy.py", line 1260, in combine_faster
 dsout[layer][:, ix: ix + ds.shape[1]] = ds[layer][ordering, 🙂
 File "/fish/simone_processing/Code/loompy/loompy/loom_layer.py", line 88, in __getitem__
 return self.ds._file['/matrix'].__getitem__(slice)
 File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
 File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
 File "/fish/simone_processing/anaconda3/envs/htc_env/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
 selection = sel.select(self.shape, args, dsid=self.id)
 File "/fish/simone_processing/anaconda3/envs/htc_env/lib/python3.7/site-packages/h5py/_hl/selections.py", line 90, in select
 sel[args]
 File "/fish/simone_processing/anaconda3/envs/htc_env/lib/python3.7/site-packages/h5py/_hl/selections.py", line 367, in __getitem__
 raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
```

**Comment by simone-codeluppi** [comment]
sorry i just saw you comments on the pysmFISH_repo. I will keep the conversation open there and test your modification
